name: Application Deployment

on:
  workflow_dispatch: # Manually triggered workflow

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
   
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan # Ensure 'terraform-plan' runs successfully first
    if: ${{ github.event.inputs.deploy == 'true' }} # Conditionally apply only if set to true
    
    steps:
      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
    
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
  
      - name: Terraform Init
        run: terraform init
    
      - name: Apply Terraform Plan
        run: terraform apply tfplan -auto-approve
